from fastapi import APIRouter

router = APIRouter(tags=["tools"])

TOOLS_CATALOG = [
    {
        "name": "search",
        "category": "search",
        "endpoint": "/api/v1/search",
        "method": "GET",
        "pricing_id": "search.query",
        "payment_required": False,
        "payment_format": None,
        "description": "Search aggregation for agent queries.",
        "expected_inputs": {"query_params": {"q": "string", "limit": "integer (optional)", "source": "string (optional)"}},
        "expected_outputs": {"data": {"results": "array of normalized search results"}},
    },
    {
        "name": "structured_web_extract",
        "category": "structured_web",
        "endpoint": "/api/v1/structured-web/extract",
        "method": "POST",
        "pricing_id": "structured_web.extract",
        "payment_required": False,
        "payment_format": None,
        "description": "Extract structured content from a URL.",
        "expected_inputs": {"json_body": {"url": "string"}},
        "expected_outputs": {"data": {"title": "string|null", "summary": "string|null", "main_text": "string", "headings": "array", "links": "array", "metadata": "object"}},
    },
    {
        "name": "structured_web_extract_html",
        "category": "structured_web",
        "endpoint": "/api/v1/structured-web/extract-html",
        "method": "POST",
        "pricing_id": "structured_web.extract_html",
        "payment_required": False,
        "payment_format": None,
        "description": "Extract structured content from raw HTML.",
        "expected_inputs": {"json_body": {"html": "string", "source_url": "string (optional)"}},
        "expected_outputs": {"data": {"title": "string|null", "summary": "string|null", "main_text": "string", "headings": "array", "links": "array", "metadata": "object"}},
    },
    {
        "name": "extract_page",
        "category": "structured_extraction",
        "endpoint": "/api/v1/extract/page",
        "method": "POST",
        "pricing_id": "extract.page",
        "payment_required": False,
        "payment_format": None,
        "description": "Fetch a page and return normalized structured JSON for agents.",
        "expected_inputs": {"json_body": {"url": "string"}},
        "expected_outputs": {"data": {"url": "string", "final_url": "string", "title": "string|null", "summary": "string|null", "emails": "array", "phone_numbers": "array", "social_links": "array", "important_links": "array", "text_excerpt": "string|null"}},
    },
    {
        "name": "company_enrich",
        "category": "company_enrichment",
        "endpoint": "/api/v1/company-enrich",
        "method": "POST",
        "pricing_id": "company.enrich",
        "payment_required": True,
        "payment_format": "base-usdc-onchain-v1",
        "description": "Run homepage-only company enrichment for a single domain.",
        "expected_inputs": {"json_body": {"domain": "string"}},
        "expected_outputs": {"data": {"domain": "string", "normalized_url": "string", "company_name": "string|null", "summary": "string|null", "industry": "string|null", "emails": "array", "phone_numbers": "array", "social_links": "array", "contact_page": "string|null", "about_page": "string|null", "careers_page": "string|null", "pricing_page": "string|null", "important_links": "array", "addresses": "array", "signals": "object", "pages_analyzed": "array"}},
    },
    {
        "name": "company_enrich_deep",
        "category": "company_enrichment",
        "endpoint": "/api/v1/company-enrich/deep",
        "method": "POST",
        "pricing_id": "company.enrich.deep",
        "payment_required": True,
        "payment_format": "base-usdc-onchain-v1",
        "description": "Run homepage company enrichment plus a capped deep pass over detected same-domain pages for a single domain.",
        "expected_inputs": {"json_body": {"domain": "string"}},
        "expected_outputs": {"data": {"domain": "string", "normalized_url": "string", "company_name": "string|null", "summary": "string|null", "industry": "string|null", "emails": "array", "phone_numbers": "array", "social_links": "array", "contact_page": "string|null", "about_page": "string|null", "careers_page": "string|null", "pricing_page": "string|null", "important_links": "array", "addresses": "array", "signals": "object", "pages_analyzed": "array"}},
    },
    {
        "name": "company_enrich_batch",
        "category": "company_enrichment",
        "endpoint": "/api/v1/company-enrich/batch",
        "method": "POST",
        "pricing_id": "company.enrich.batch",
        "payment_required": True,
        "payment_format": "base-usdc-onchain-v1",
        "description": "Run homepage-only company enrichment for up to 10 domains and return per-domain results.",
        "expected_inputs": {"json_body": {"domains": "array<string> (max 10)"}},
        "expected_outputs": {"data": {"results": "array", "count": "integer", "success_count": "integer", "error_count": "integer"}},
    },
    {
        "name": "company_enrich_deep_batch",
        "category": "company_enrichment",
        "endpoint": "/api/v1/company-enrich/deep/batch",
        "method": "POST",
        "pricing_id": "company.enrich.deep.batch",
        "payment_required": True,
        "payment_format": "base-usdc-onchain-v1",
        "description": "Run deep company enrichment for up to 10 domains and return per-domain results.",
        "expected_inputs": {"json_body": {"domains": "array<string> (max 10)"}},
        "expected_outputs": {"data": {"results": "array", "count": "integer", "success_count": "integer", "error_count": "integer"}},
    },
    {
        "name": "memory_store",
        "category": "agent_memory",
        "endpoint": "/api/v1/memory/store",
        "method": "POST",
        "pricing_id": "memory.store",
        "payment_required": False,
        "payment_format": None,
        "description": "Store a short text memory for an agent.",
        "expected_inputs": {"json_body": {"agent_id": "string", "scope": "string", "content": "string", "metadata": "object (optional)"}},
        "expected_outputs": {"data": {"memory_id": "string", "agent_id": "string", "scope": "string", "content": "string", "metadata": "object", "created_at": "string"}},
    },
    {
        "name": "memory_search",
        "category": "agent_memory",
        "endpoint": "/api/v1/memory/search",
        "method": "POST",
        "pricing_id": "memory.search",
        "payment_required": True,
        "payment_format": "base-usdc-onchain-v1",
        "description": "Search an agent's stored memories with deterministic text matching.",
        "expected_inputs": {"json_body": {"agent_id": "string", "query": "string", "limit": "integer (optional)", "scope": "string (optional)"}},
        "expected_outputs": {"data": {"results": "array"}},
    },
    {
        "name": "memory_delete",
        "category": "agent_memory",
        "endpoint": "/api/v1/memory/delete",
        "method": "POST",
        "pricing_id": "memory.delete",
        "payment_required": False,
        "payment_format": None,
        "description": "Delete a stored memory by memory_id.",
        "expected_inputs": {"json_body": {"memory_id": "string"}},
        "expected_outputs": {"data": {"deleted": "boolean", "memory_id": "string"}},
    },
    {
        "name": "lead_extract_url",
        "category": "lead_extraction",
        "endpoint": "/api/v1/lead-extract",
        "method": "POST",
        "pricing_id": "lead_extract.url",
        "payment_required": True,
        "payment_format": "base-usdc-onchain-v1",
        "description": "Extract contact and lead information from a URL.",
        "expected_inputs": {"json_body": {"url": "string"}},
        "expected_outputs": {"data": {"emails": "array", "phone_numbers": "array", "social_media_links": "array", "company_name": "string|null", "contact_forms_detected": "boolean", "addresses": "array"}},
    },
    {
        "name": "lead_extract_html",
        "category": "lead_extraction",
        "endpoint": "/api/v1/lead-extract",
        "method": "POST",
        "pricing_id": "lead_extract.html",
        "payment_required": True,
        "payment_format": "base-usdc-onchain-v1",
        "description": "Extract contact and lead information from raw HTML.",
        "expected_inputs": {"json_body": {"html": "string", "source_url": "string (optional)"}},
        "expected_outputs": {"data": {"emails": "array", "phone_numbers": "array", "social_media_links": "array", "company_name": "string|null", "contact_forms_detected": "boolean", "addresses": "array"}},
    },
]


@router.get("/tools")
async def get_tools() -> dict:
    return {"ok": True, "data": {"tools": TOOLS_CATALOG}}
